### ISSUE TITLE
Excess API call when using mandrill templates

### ISSUE THREAD

**Issue by kozmenkoav** [nickcv-ln/yii2-mandrill#3]
To send a message using external templates your component makes 2 API calls. First call to render template, second to send a message. To get rid of the first one you can use function /mandrill/src/Mandrill/Messages.php::sendTemplate() function, which makes 'messages/send-template' API call.
Thanks for your work!

**Comment by nickcv-ln** [comment]
I completely agree with you.

The feature was implemented after someone made a pull request and for some reason the guy wanted to just retrieve the template from mandrill when compose was called instead of sending the email using the template directly.

I could definitely change the logic to avoid making two separate API calls, the only issue would be that if I don't retrieve the template when compose is called that would mean that the getHtml method of the message object returned by compose would return null.

**Comment by kozmenkoav** [comment]
> I could definitely change the logic to avoid making two separate API calls, the only issue would be that if I don't retrieve the template when compose is called that would mean that the getHtml method of the message object returned by compose would return null.

It's ok in case of using external templates.

Would be great if developer could enable/disable async mode via component settings.

**Comment by nickcv-ln** [comment]
Perfect,

I'll make those changes and add the option for async mode

**Comment by kozmenkoav** [comment]
I've made quick update for my project https://github.com/kozmenkoav/yii2-mandrill/commit/68362c80ee39e636ff3b61e8c2de9ee800b9681e
I hope it will be useful for you.

**Comment by nickcv-ln** [comment]
Version 1.3.0 has just been released!

Now send-template is being used instead of rendering them beforehand.
An async method has also been added to the message.
