### ISSUE TITLE
Not able to send mail.

### ISSUE THREAD

**Issue by TuringThinker** [nickcv-ln/yii2-mandrill#7]
Hi nick,

I am facing problem with mandrill extension when I am trying to send mail from Swift Mailer. I have attached the screenshot and my code below.

web.php
'mailer' => [
            'class' => 'nickcv\mandrill\Mailer',
            'apikey' => '****_j0X0ZHi6mlvw**_**'
        ],

controller

protected function sendMail($setTo,$setSubject,$setTextBody)
    {
        Yii::$app->mailer->compose()
            ->setFrom('*****@gmail.com')
            ->setTo($setTo)
            ->setSubject($setSubject)
            ->setTextBody($setTextBody)
            ->send();
    }

![yii-base-errorexception](https://cloud.githubusercontent.com/assets/12469565/7859417/76bf94cc-055e-11e5-88dd-13cefd556029.png)

And I have curl installed in my machine. I don't know what to do. Please help. Thanks in advance.

**Comment by nickcv-ln** [comment]
According to the screenshot you sent curl is not installed properly.
You can either check the modules you have installed by using the following command in your terminal

```
php -m | grep curl
```

or by creating a php file containing the `phpinfo();` function.

![screenshot from 2015-05-28 13 49 57](https://cloud.githubusercontent.com/assets/8384804/7860394/7b0d1b9e-0540-11e5-885f-e2392e488d58.png)

**Comment by TuringThinker** [comment]
I had checked for curl in my machine and attached the screenshot for phpinfo and output of the command.

![phpinfo](https://cloud.githubusercontent.com/assets/12469565/7876694/87558906-05ed-11e5-88d4-5865c9ed50f7.png)

![screenshot from 2015-05-29 10 30 24](https://cloud.githubusercontent.com/assets/12469565/7876717/00264410-05ee-11e5-9372-b6b2414f7a67.png)

Should I remove curl and reinstall it again ? But curl is working fine for my other projects.

**Comment by nickcv-ln** [comment]
are you using fast-cgi for php? do you have separate ini files for each project?
because according to the error posted it dies as soon as it tries to init curl, claiming that the function is not there.

Try on a new controller of your application to execute directly the curl_init function and see if that is throwing an exception.

**Comment by TuringThinker** [comment]
![phpinfo](https://cloud.githubusercontent.com/assets/12469565/7879834/9929b822-0611-11e5-8f2b-39ff6dd08136.png)

This is screenshot for fastCGI stuffs and I have no separate ini files for each project.

I tried curl_init() on a new controller 
1.
controller 
public function actionTest()
    {
        curl_init();
    }

output
blank screen ( no errors and no outputs)

2.
controller 
public function actionTest()
    {
        print_r(curl_init());
    }

output
Resource id #2

**Comment by nickcv-ln** [comment]
This is definitely weird, but the error being thrown is "call to undefined function curl_init"

The call is also made by [Mandrill's own package](https://bitbucket.org/mailchimp/mandrill-api-php), which I'm just wrapping.

I do recommend that you try reinstalling curl from scratch because I don't think that the error lies in Mandrill's own library.
